# Generated by Django 5.0 on 2023-12-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='images/None/noimg.jpg', upload_to='images/'),
        ),
    ]
